---
- name: "Preflight - Fail if target host is not stable for this Role."
  fail:
    msg: "This role is not stable for the target operating system, {{ ansible_distribution }} {{ ansible_distribution_major_version }}."
  when: (ansible_distribution is not defined) or
        (ansible_distribution_version is not defined) or
        (ansible_distribution+" "+ansible_distribution_major_version not in meilisearch_stable_os)

- name: "Register MeiliSearch Installation Status."
  stat:
    path: "{{ meilisearch_exe_path }}"
  register: meilisearch_status

- name: "Create Meilisearch Group."
  group:
    name: "{{ meilisearch_group }}"
    system: 'yes'
    state: present

- name: "Create Meilisearch User."
  user:
    name: "{{ meilisearch_user }}"
    password_lock: 'yes'
    groups: "{{ meilisearch_group }}"
    shell: '/bin/nologin'
    system: 'yes'
    state: present

- name: "Get MeiliSearch Installation Script."
  get_url:
    url: https://install.meilisearch.com
    dest: "/tmp/meilisearch.sh"
    mode: 0750
    owner: root
  when: not meilisearch_status.stat.exists | bool

- name: "Run MeiliSearch Installation Script."
  shell: /tmp/meilisearch.sh
  args:
    chdir: /tmp
    # warn: 'false'
  when: not meilisearch_status.stat.exists | bool

- name: "Move MeiliSearch Binary into Place."
  shell: mv /tmp/meilisearch "{{ meilisearch_exe_path }}"
  args:
    chdir: /tmp
    # warn: 'false'
  when: not meilisearch_status.stat.exists | bool

- name: "Ensure Permissions on MeiliSearch Binary."
  file:
    path: "{{ meilisearch_exe_path }}"
    mode: 0750
    owner: "{{ meilisearch_user }}"
    group: "{{ meilisearch_group }}"

- name: "Ensure MeiliSearch DB Directory exists."
  file:
    path: "{{ item }}"
    mode: 0750
    owner: "{{ meilisearch_user }}"
    group: "{{ meilisearch_group }}"
    state: directory
  loop: 
    - "{{ meilisearch_db_path }}"
    - "{{ meilisearch_cfg_db_path }}"
    - "{{ meilisearch_cfg_dump_dir }}"
    - "{{ meilisearch_cfg_snapshot_dir }}"

- name: "Copy MeiliSearch config file."
  template:
    src: config.toml.j2
    dest: "{{ meilisearch_configfile }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart meilisearch

- name: "Copy MeiliSearch systemd unit file into place."
  template:
    src: meilisearch.unit.j2
    dest: /etc/systemd/system/meilisearch.service
    owner: root
    group: root
    mode: 0644
  when: "ansible_service_mgr == 'systemd'"
  notify:
    - systemd daemon-reload
    - restart meilisearch

- name: "Configure the MeiliSearch Service."
  service:
    name: meilisearch
    state: "{{ meilisearch_state }}"
    enabled: "{{ meilisearch_enabled_at_boot }}"
